# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [3]:
import numpy as np
arr = np.zeros(100)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [4]:
import numpy as np
arr = np.ones(100)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [5]:
import numpy as np
arr = np.full(100, 3)
print(arr)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [20]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-20-e4a7e6a4f2e9>, line 1)

#### 5. Поменять 2 строки в матрице

In [19]:
import numpy as np
arr = np.arange(4).reshape(2,2)
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[2 3]
 [0 1]]


#### 6. Создать вектор со значениями от 10 до 100

In [11]:
import numpy as np
arr = np.arange(10, 100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 7. Развернуть вектор (первый становится последним)

In [12]:
import numpy as np
arr = np.arange(10)
arr = arr[:: -1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [15]:
import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [17]:
import numpy as np
arr0 = np.array([1,2,3,4,5])
arr1 = np.zeros(len(arr0) + (len(arr0)-1) * 3) 
arr1[::4] = arr0
print(arr1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [21]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [23]:
import numpy as np
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.02706481 0.5742944  0.60731702]
  [0.84697827 0.44285787 0.75305409]
  [0.81180774 0.8279433  0.66326347]]

 [[0.71394785 0.76184278 0.76813543]
  [0.85360386 0.29309449 0.97301789]
  [0.82592058 0.53536991 0.9110111 ]]

 [[0.58888069 0.64583082 0.97383209]
  [0.08334727 0.56719653 0.43987558]
  [0.85746708 0.28598906 0.66897908]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [25]:
import numpy as np
arr = np.random.random((10,10))
min = arr.min()
max = arr.max()
print(min, max)

0.0029261462288794338 0.9972662182138687


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [26]:
import numpy as np
arr = np.random.random(30)
med = arr.mean()
print(med)

0.47672110335272666


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [28]:
import numpy as np
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [29]:
import numpy as np

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [30]:
import numpy as np
arr = np.diag(np.arange(1, 5), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [31]:
import numpy as np
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [32]:
import numpy as np
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [33]:
import numpy as np
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [34]:
import numpy as np
arr = np.dot(np.zeros((5, 3)), np.zeros((3,2)))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [35]:
import numpy as np
arr = np.arange(11)
arr[(arr > 3) & (arr < 8)] *= -1

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [36]:
import numpy as np
arr = np.zeros((5,5))
arr = arr + np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

In [37]:
import numpy as np
xrange
def generate():
    for x in xrange(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1)
print(arr)

NameError: name 'xrange' is not defined

25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [38]:
import numpy as np
arr = np.linspace(0,1,12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [39]:
import numpy as np
arr = np.random.random(10)
arr.sort()
print(arr)

[0.09395688 0.14735928 0.20921631 0.26048076 0.49016534 0.61774536
 0.69731047 0.79165158 0.86402968 0.99497773]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [41]:
import numpy as np
arr0 = np.random.randint(0,1,4)
arr1 = np.random.randint(0,1,4)
equal = np.allclose(arr0,arr1)
print(equal)

True


#### 28. Сделать массив неизменяемым

In [45]:
import numpy as np
arr = np.zeros(5)
arr.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [46]:
import numpy as np
arr = np.arange(10000)
np.random.shuffle(arr)
n = 2
print (arr[np.argpartition(-arr,n)[:n]])

[9999 9998]


#### 30. Заменить максимальный элемент на ноль

In [47]:
import numpy as np
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.44065238 0.52691119 0.02544787 0.79186263 0.32869705 0.
 0.33651778 0.64067128 0.62423663 0.02746462]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [49]:
import numpy as np
arr = np.zeros((10,10), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(arr)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [50]:
import numpy as np
arr0 = np.arange(5)
arr1 = arr0 + 0.5
C = 1.0 / np.subtract.outer(arr0, arr1)
print(np.linalg.det(C))

-131.91659501325745


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [51]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [52]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [53]:
import numpy as np
arr = np.arange(100)
c = np.random.uniform(0,100)
i = (np.abs(arr-c)).argmin()
print(arr[i])

15


#### 36. Преобразовать массив из float в int

In [54]:
import numpy as np
arr = np.arange(10, dtype=np.int32)
arr = arr.astype(np.float32, copy=False)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [55]:
import numpy as np
arr = np.arange(9).reshape(3,3)
for i, v in np.ndenumerate(arr):
    print(i, v)
for i in np.ndindex(arr.shape):
    print(i, arr[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [56]:
import numpy as np
p = 2
arr = np.zeros((5,5))
np.put(arr, np.random.choice(range(5*5), p, replace=False), 1)
print(arr)

[[0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [57]:
import numpy as np
arr = np.random.rand(5, 10)
arr0 = arr - arr.mean(axis=1, keepdims=True)
print(arr0)

[[-0.47450205  0.27294066  0.32490207 -0.56134575 -0.04080575 -0.04055779
   0.26669407  0.33554396 -0.41489996  0.33203055]
 [ 0.30498628 -0.46766182  0.0587993  -0.07496602  0.3965921  -0.06542967
   0.45021247 -0.50324544  0.4220441  -0.52133131]
 [-0.2566605   0.19770723  0.04218664  0.15450206  0.20931925 -0.2816648
   0.09020605  0.06681967 -0.25735753  0.03494193]
 [-0.42542878  0.37381947 -0.11477093  0.05964903  0.17051618 -0.34593173
   0.10738537 -0.05470156 -0.17966032  0.40912326]
 [ 0.08338489  0.19231083  0.28204142 -0.16193427  0.29974134 -0.45403428
  -0.12364913  0.1301088  -0.50487209  0.25690251]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [60]:
import numpy as np
arr = np.random.randint(0,2,(3,3))
n = 2
print(arr)
print(arr[arr[:,n].argsort()])

[[1 1 1]
 [1 1 1]
 [0 1 0]]
[[0 1 0]
 [1 1 1]
 [1 1 1]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [61]:
import numpy as np
arr = np.random.randint(0,3,(0,10))
print((~arr.any(axis=0)).any())

True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [62]:
import numpy as np
arr = np.ones(10)
arr0 = np.random.randint(0,len(arr),20)
arr += np.bincount(arr0, minlength=len(arr))
print(arr)

[3. 5. 5. 4. 2. 1. 2. 3. 2. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [63]:
import numpy as np
w = 10
h = 16
arr0 = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
arr1 = arr0[...,0] * 256 * 256 + arr0[...,1] * 256 + arr0[...,2]
print(np.unique(arr0))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
import numpy as np
arr = np.random.randint(0,10, (3,4,3,4))
sum = arr.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)